spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_dbcar?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useAffectedRows=true
    username: root
    password: root
    diver-class-name: com.mysql.jdbc.Driver